### ISSUE TITLE
Lunar theme, where to download it?

### ISSUE THREAD

**Issue by renato-ll** [JamDesuGa/AHK-for-Notepad-#1]
Lunar theme, where to download it? :(

**Comment by jamunano** [comment]
the post may have been deleted...
or the lunar theme may have been discontinued idk IDK.....

**Comment by renato-ll** [comment]
Dont you have it ? :D

**Comment by jamunano** [comment]
i just tried my best to match with the original

**Comment by jamunano** [comment]
this is the original lunar theme
all i did was just take the color codes and placed them in xml or something idk i forgot
just use this as a reference and make your own theme ¯\_(ツ)_/¯

**Comment by meyerdg** [comment]
Updated link to the forum post -> https://forum.facepunch.com/t/lunar-a-sleek-and-beautiful-theme-for-notepad/119181

Link to the goods as posted within the forum post -> http://www.mediafire.com/?5n0e3g7x3oh2jyq

Thank you and have a nice day.

edit: I'll just leave this here -- https://github.com/meyerdg/lunartheme

**Comment by jamunano** [comment]
thank you <3
